name: Build payload

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: john-tornblom/ps5-payload-sdk
        path: ps5-payload-sdk

    - name: Setup SDK
      working-directory: ps5-payload-sdk
      run: |
        sudo apt update
        sudo apt install wget build-essential python3 python3-pyelftools clang lldb
        make
        make DESTDIR=${{ runner.tool_cache }}/ps5-payload-sdk install
        echo PS5_PAYLOAD_SDK=${{ runner.tool_cache }}/ps5-payload-sdk >> $GITHUB_ENV
        echo PS5_HOST=ps5 >> $GITHUB_ENV
        echo PS5_PORT=9020 >> $GITHUB_ENV

    - name: Build PS5 Webkit (inproc)
      run: |
        make clean all
        mkdir -p payloads
        mv ftp-server.elf payloads/ftp-server.webkit.inproc.elf

    - name: Build PS5 Webkit (fork)
      run: |
        make FORK_SERVER=1 clean all
        mkdir -p payloads
        mv ftp-server.elf payloads/ftp-server.webkit.fork.elf

    - name: Build PS5 BD-J (inproc)
      run: |
        make MTRW_COMMAND=1 clean all
        mkdir -p payloads
        mv ftp-server.elf payloads/ftp-server.bdj.inproc.elf

    - name: Build Ubuntu (inproc)
      run: |
        make -f Makefile.posix clean all
        mkdir -p payloads
        mv ftp-server.elf payloads/ftp-server.ubuntu.inproc.elf

    - name: Build Ubuntu (fork)
      run: |
        make FORK_SERVER=1 -f Makefile.posix clean all
        mkdir -p payloads
        mv ftp-server.elf payloads/ftp-server.ubuntu.fork.elf

    - name: Upload payloads
      uses: actions/upload-artifact@v3
      with:
        name: Payload binaries
        path: payloads/*.elf
        if-no-files-found: error
